targets:
  $default:
    builders:
      flutter_gen:
        enabled: true
#  flutter_gen:json:
#    builders:
#      json_serializable:
#        options:
#          any_map: true
#          checked: true
#          create_factory: true
#          create_to_json: true
#          disallow_unrecognized_keys: false
#          explicit_to_json: false
#          field_rename: none
#          generic_argument_factories: false
#          ignore_unannotated: false
#          include_if_null: true
#          nullable: true


builders:
  flutter_gen:
    import: "package:flutter_gen/build.dart"
    builder_factories: [ "build" ]
    build_extensions: { "$lib$": [ ".gen.dart" ] }
    auto_apply: dependents
    build_to: source
