codecov:
  notify:
    wait_for_ci: true
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        # basic
        target: 0%
        threshold: 0%
        base: auto
        # advanced
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags: null
        paths: null

ignore:
  - 'examples/**/*'
  - '**/*.g.dart'
  - '**/*.gen.dart'
