name: FlutterGen

packages:
  - packages/**
  - examples/**

ide:
  intellij: true
  vscode: true

command:
  clean:
    hooks:
      post:
        run: |
          melos exec -c 6 -- flutter clean
        description: flutter clean

scripts:
  get:
    exec: flutter pub get
    description: flutter pub get

  upgrade:
    exec: flutter pub upgrade
    description: flutter pub upgrade

  analyze:
    run: flutter analyze
    description: flutter analyze

  format:
    run: dart format --set-exit-if-changed .
    description: dart format --set-exit-if-changed .

  build:
    exec: flutter build apk
    packageFilters:
      scope: example
    description: flutter build apk

  gen:build_runner:
    exec: dart pub run build_runner build --delete-conflicting-outputs
    packageFilters:
      ignore:
        - example
        - example_resources
      dependsOn: build_runner
    description: dart pub run build_runner build --delete-conflicting-outputs

  gen:example:command:
    exec: dart ../../packages/command/bin/flutter_gen_command.dart --config pubspec.yaml
    packageFilters:
      scope: example
    description: dart ../../packages/command/bin/flutter_gen_command.dart --config pubspec.yaml

  gen:example:build_runner:
    exec: flutter pub run build_runner build --delete-conflicting-outputs
    packageFilters:
      scope: example
    description: flutter pub run build_runner build --delete-conflicting-outputs

  gen:example:res:command:
    exec: dart ../../packages/command/bin/flutter_gen_command.dart --config pubspec.yaml
    packageFilters:
      scope: example_resources
    description: dart ../../packages/command/bin/flutter_gen_command.dart --config pubspec.yaml

  gen:example:res:build_runner:
    exec: flutter pub run build_runner build --delete-conflicting-outputs
    packageFilters:
      scope: example_resources
    description: flutter pub run build_runner build --delete-conflicting-outputs

  test:
    run: melos test:dart --no-select
    description: dart test

  test:dart:
    run: dart test
    exec:
      failFast: true
    packageFilters:
      flutter: false
      dependsOn: test
    description: dart test

  coverage:
    run: |
      bash ./scripts/coverage.sh packages/core
    description: bash ./scripts/coverage.sh packages/core
