name: FlutterGen

packages:
  - packages/**
  - example/*

ide:
  intellij: true
  vscode: true

scripts:
  pub:upgrade:
    run: |
      melos exec -- flutter pub upgrade

  analyze: melos exec -- dart analyze .

  format: bash ./scripts/dartfmt.sh

  gen:build_runner:
    run: |
      melos exec -- dart pub run build_runner build --delete-conflicting-outputs
    select-package:
      ignore: example
      depends-on: 'build_runner'

  build:
    run: |
      melos exec -- flutter build apk
    select-package:
      scope: example

  example:command:
    run: |
      melos exec \
      -- dart ../packages/command/bin/flutter_gen_command.dart --config pubspec.yaml
    select-package:
      scope: example

  example:build_runner:
    # FIXME: https://github.com/invertase/melos/issues/117
    # run: |
    #   melos exec \
    #   -- flutter pub run build_runner build --delete-conflicting-outputs
    run: |
      melos exec \
      -- dart pub global run build_runner build --delete-conflicting-outputs
    select-package:
      scope: example

  unit:test:
    run: melos exec -- dart run test
    select-package:
      dir-exists: test

  coverage:
    run: |
      bash ./scripts/coverage.sh packages/core
      bash ./scripts/codecov.sh ${CODECOV_TOKEN}
