name: flutter_assets_gen_repository
description: A specialized asset generator for Flutter with support for multiple asset classes and custom groupings.
version: 1.0.0
homepage: https://github.com/Sumat-Dev/flutter_assets_gen
repository: https://github.com/Sumat-Dev/flutter_assets_gen

environment:
  sdk: ^3.4.0

dev_dependencies:
  lints: any # Ignoring the version to allow editing across SDK versions.
  melos: ^6.0.0
