// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'assets_gen_integrations_test.dart' as assets_gen_integrations_test;
import 'assets_gen_test.dart' as assets_gen_test;
import 'colors_gen_test.dart' as colors_gen_test;
import 'config_test.dart' as config_test;
import 'flutter_gen_test.dart' as flutter_gen_test;
import 'fonts_gen_test.dart' as fonts_gen_test;

void main() {
  config_test.main();
  flutter_gen_test.main();
  assets_gen_integrations_test.main();
  fonts_gen_test.main();
  assets_gen_test.main();
  colors_gen_test.main();
}
