# Composite Action
# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
name: 'Setup SDKs'
description: 'Dart, Flutter, and Melos'
runs:
  using: "composite"
  steps:
    - uses: subosito/flutter-action@v2
      with:
        channel: stable

    - uses: dart-lang/setup-dart@v1
      with:
        sdk: stable

    - name: Set environment for Ubuntu and macOS
      shell: bash
      run: |
        if [ "${{ runner.os }}" == "Linux" ] || [ "${{ runner.os }}" == "macOS" ] ; then
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
        fi
    - name: Set environment for Windows
      shell: pwsh
      run: |
        if [ "${{ runner.os }}" == "Windows" ]; then
          echo "%LOCALAPPDATA%\Pub\Cache\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        fi

    - name: Get dependencies for Ubuntu and macOS
      shell: bash
      run: |
        if [ "${{ runner.os }}" == "Linux" ] || [ "${{ runner.os }}" == "macOS" ] ; then
          dart pub global activate melos
          melos bootstrap
        fi
    - name: Get dependencies for Windows
      shell: pwsh
      run: |
        if [ "${{ runner.os }}" == "Windows" ]; then
          dart pub global activate melos
          # FIXME: CI randomly fail
          melos exec -c 1 -- flutter pub get
          melos bootstrap
        fi
