name: 'Setup SDKs'
description: 'Dart, Flutter, and Melos'
runs:
  using: "composite"
  steps:
    - uses: subosito/flutter-action@v2
      with:
        channel: stable

    - uses: dart-lang/setup-dart@v1
      with:
        sdk: stable

    - name: Set environment
      shell: bash
      run: |
        if startsWith(matrix.os, 'macos') || startsWith(matrix.os, 'ubuntu'); then
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
        elif startsWith(matrix.os, 'windows')
          run: echo "%LOCALAPPDATA%\Pub\Cache\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        fi

    - name: Get dependencies
      if: startsWith(matrix.os, 'macos') || startsWith(matrix.os, 'ubuntu')
      shell: bash
      run: |
        if startsWith(matrix.os, 'macos') || startsWith(matrix.os, 'ubuntu'); then
          dart pub global activate melos
          melos bootstrap
        elif startsWith(matrix.os, 'windows')
          dart pub global activate melos
          # FIXME: CI randomly fail
          melos exec -c 1 -- flutter pub get
          melos bootstrap
        fi
