name: flutter_assets_gen_runner
description: build_runner support for flutter_assets_gen.
version: 1.0.0
homepage: https://github.com/Sumat-Dev/flutter_assets_gen
repository: https://github.com/Sumat-Dev/flutter_assets_gen/tree/main/packages/runner
documentation: https://github.com/Sumat-Dev/flutter_assets_gen
issue_tracker: https://github.com/Sumat-Dev/flutter_assets_gen/issues

environment:
  sdk: ^3.4.0

dependencies:
  flutter_assets_gen_core: ^1.0.0
  build: ^4.0.0
  build_config: ^1.1.2
  collection: ^1.17.0
  crypto: ^3.0.0
  glob: ^2.0.0
  package_config: ^2.1.0
  path: ^1.8.0
  yaml: ^3.0.0

dev_dependencies:
  lints: any # Ignoring the version to allow editing across SDK versions.
  test: ^1.25.0
