name: flutter_assets_gen
description: A specialized asset generator for Flutter with support for multiple asset classes and custom groupings.
version: 1.0.0
homepage: https://github.com/Sumat-Dev/flutter_assets_gen
repository: https://github.com/Sumat-Dev/flutter_assets_gen/tree/main/packages/command
documentation: https://github.com/Sumat-Dev/flutter_assets_gen
issue_tracker: https://github.com/Sumat-Dev/flutter_assets_gen/issues

environment:
  sdk: ^3.4.0

executables:
  flutter_assets_gen: flutter_assets_gen_command

dependencies:
  flutter_assets_gen_core: ^1.0.0

  args: ^2.0.0
  glob: ^2.1.3
  logging: ^1.3.0
  path: ^1.9.1
  yaml: ^3.1.3

dev_dependencies:
  lints: any # Ignoring the version to allow editing across SDK versions.
  test: ^1.16.0
  test_process: ^2.0.0
