name: Auto self assign

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  assign:
    if: |
      github.event.pull_request.user.type == 'User'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const assignees = context.payload.pull_request.assignees
            if (!assignees || assignees.length === 0) {
              github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                assignees: `${{ github.actor }}`,
              })
            }
