name: Build

on:
  pull_request: {}
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Run on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-sdks

      - name: Run tests for our dart project.
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          melos run unit:test

      - name: Run coverage
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          melos run coverage

      - name: Generate example
        run: |
          melos run example:command
          melos run example:build_runner

      - name: Check for any formatting and statically analyze the code.
        run: |
          melos run format
          melos run analyze
