name: Flutter CI

on:
  pull_request: { }
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build:
    name: Run on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Get dart dependencies.
        run: make dependencies

      - name: Run tests for our dart project.
        run: |
          make unit-test
          make coverage

      - name: Generate example
        run: |
          make generate-with-command
          make generate-with-runner

      - name: Check for any formatting and statically analyze the code.
        run: |
          make format
          make analyze
