name: 'Setup SDKs'

jobs:
  setup:
    name: Run on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Set environment for macOS and Ubuntu
        if: startsWith(matrix.os, 'macos') || startsWith(matrix.os, 'ubuntu')
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Set environment for Windows
        if: startsWith(matrix.os, 'windows')
        run: echo "%LOCALAPPDATA%\Pub\Cache\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Get dependencies for macOS and Ubuntu
        if: startsWith(matrix.os, 'macos') || startsWith(matrix.os, 'ubuntu')
        run: |
          dart pub global activate melos
          melos bootstrap

      - name: Get dependencies for Windows
        if: startsWith(matrix.os, 'windows')
        run: |
          dart pub global activate melos
          # FIXME: CI randomly fail
          melos exec -c 1 -- flutter pub get
          melos bootstrap
